#!/usr/bin/env python3
"""
build_graph.py — the ONE source of truth for the machine + human views.

Parses families/*/CONTEXT_GRAPH.md (the canonical, agent-readable maps) and emits:
  - graph.json        machine representation (what a foreign agent can load instead
                      of walking the markdown)
  - viz/index.html    a self-contained, dependency-free force-directed picture

It also VERIFIES the graph is symmetric (every braid points both ways) and that the
machine view agrees with the markdown the AI voice routes on — if they ever diverge,
this exits non-zero instead of shipping a lie. Re-run after editing any family map.

    python3 tools/build_graph.py
"""
import re, glob, os, json, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FAM = os.path.join(ROOT, "families")

NODES = ['anger','grief','self-compassion','joy','love','fear','excitement',
         'calm','solidarity','held-tension','senses','body-awareness','relief']
ALIAS = {n: n for n in NODES}
ALIAS.update({'courage': 'fear', 'a chosen move': 'fear', 'chosen move': 'fear'})

HTML = r"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>emotions-and-humor — braid graph</title>
<!-- Self-contained: no external requests. Generated by tools/build_graph.py.
     Human view only. The agent-facing router is CONTEXT_GRAPH.md; the machine
     view is graph.json. This picture is a projection of the same source. -->
<style>
  :root{
    --bg:#f7f7f9; --panel:#ffffff; --text:#1c1d22; --muted:#6b6f7a;
    --edge:#c7cad3; --edge-hi:#6366f1; --emotion:#6366f1; --dual:#14b8a6;
    --stroke:#ffffff; --shadow:0 1px 3px rgba(0,0,0,.12),0 6px 20px rgba(0,0,0,.06);
  }
  @media (prefers-color-scheme:dark){
    :root{--bg:#101118;--panel:#181a22;--text:#e9eaf0;--muted:#9aa0ad;
      --edge:#333747;--edge-hi:#8b8ffb;--emotion:#8b8ffb;--dual:#2dd4bf;--stroke:#101118;
      --shadow:0 1px 3px rgba(0,0,0,.4),0 8px 28px rgba(0,0,0,.35);}
  }
  :root[data-theme=light]{--bg:#f7f7f9;--panel:#fff;--text:#1c1d22;--muted:#6b6f7a;
    --edge:#c7cad3;--edge-hi:#6366f1;--emotion:#6366f1;--dual:#14b8a6;--stroke:#fff;}
  :root[data-theme=dark]{--bg:#101118;--panel:#181a22;--text:#e9eaf0;--muted:#9aa0ad;
    --edge:#333747;--edge-hi:#8b8ffb;--emotion:#8b8ffb;--dual:#2dd4bf;--stroke:#101118;}
  *{box-sizing:border-box}
  html,body{margin:0;height:100%}
  body{background:var(--bg);color:var(--text);
    font:15px/1.5 ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,sans-serif;}
  header{display:flex;align-items:baseline;gap:14px;flex-wrap:wrap;
    padding:16px 20px 8px}
  header h1{font-size:18px;margin:0;font-weight:650}
  header .sub{color:var(--muted);font-size:13px}
  header .sp{flex:1}
  button{font:inherit;color:var(--text);background:var(--panel);cursor:pointer;
    border:1px solid var(--edge);border-radius:8px;padding:6px 12px}
  button:hover{border-color:var(--edge-hi)}
  main{display:flex;gap:16px;padding:8px 16px 16px;align-items:stretch;
    height:calc(100% - 64px);min-height:520px}
  #wrap{position:relative;flex:1;min-width:0;background:var(--panel);
    border:1px solid var(--edge);border-radius:14px;overflow:hidden;box-shadow:var(--shadow)}
  svg{width:100%;height:100%;display:block;touch-action:none}
  .link{stroke:var(--edge);stroke-width:1.4;transition:stroke .12s,stroke-width .12s}
  .link.hi{stroke:var(--edge-hi);stroke-width:2.6}
  .link.dim{opacity:.18}
  .node circle{stroke:var(--stroke);stroke-width:2;cursor:pointer;transition:opacity .12s}
  .node.dual circle{stroke:var(--dual);stroke-width:3.5}
  .node text{fill:var(--text);font-size:12px;pointer-events:none;
    paint-order:stroke;stroke:var(--panel);stroke-width:3px;stroke-linejoin:round}
  .node.hub text{font-weight:700;font-size:13px}
  .node.dim{opacity:.22}
  aside{width:290px;flex:none;background:var(--panel);border:1px solid var(--edge);
    border-radius:14px;box-shadow:var(--shadow);padding:16px 18px;overflow:auto}
  @media (max-width:760px){main{flex-direction:column;height:auto}
    aside{width:auto}#wrap{height:60vh}}
  aside h2{margin:0 0 2px;font-size:17px}
  aside .preset{color:var(--muted);font-size:13px;margin-bottom:12px}
  aside .chip{display:inline-block;font-size:11px;padding:2px 8px;border-radius:20px;
    border:1px solid var(--edge);color:var(--muted);margin:0 6px 10px 0}
  aside .lbl{font-size:11px;text-transform:uppercase;letter-spacing:.06em;
    color:var(--muted);margin:14px 0 6px}
  aside .braid{margin:0 0 9px;padding-left:14px;position:relative}
  aside .braid b{font-weight:650}
  aside .braid::before{content:'';position:absolute;left:0;top:8px;width:6px;height:6px;
    border-radius:50%;background:var(--edge-hi)}
  aside .empty{color:var(--muted)}
  .legend{position:absolute;left:12px;bottom:12px;font-size:12px;color:var(--muted);
    background:var(--panel);border:1px solid var(--edge);border-radius:8px;padding:8px 10px}
  .legend .row{display:flex;align-items:center;gap:7px;margin:2px 0}
  .legend .dot{width:11px;height:11px;border-radius:50%}
  .tip{position:fixed;pointer-events:none;background:var(--panel);color:var(--text);
    border:1px solid var(--edge);border-radius:8px;padding:7px 10px;font-size:12.5px;
    max-width:280px;box-shadow:var(--shadow);opacity:0;transition:opacity .1s;z-index:9}
  .hint{color:var(--muted);font-size:12.5px;padding:0 4px}
</style>
</head>
<body>
<header>
  <h1>emotions &amp; humor — the braid graph</h1>
  <span class="sub">nodes sized by degree · drag to rearrange · tap a feeling for its braids</span>
  <span class="sp"></span>
  <button id="reheat">shuffle</button>
  <button id="theme">theme</button>
</header>
<main>
  <div id="wrap">
    <svg id="g"></svg>
    <div class="legend">
      <div class="row">node hue = the family's Spectrum color</div>
      <div class="row"><span class="dot" style="background:transparent;border:3px solid var(--dual)"></span>teal ring = dual (also a body attacher)</div>
    </div>
  </div>
  <aside id="panel">
    <p class="hint">A force-directed picture of the 12 families and the braids
    between them. The hubs that drift to the center — <b>grief</b> and <b>fear</b> —
    are the great modulators: they thread under nearly every other feeling. Click
    a node to read its braids.</p>
  </aside>
</main>
<div class="tip" id="tip"></div>
<script>
const GRAPH = __GRAPH_DATA__;
const SVGNS='http://www.w3.org/2000/svg';
const svg=document.getElementById('g'), wrap=document.getElementById('wrap');
const tip=document.getElementById('tip'), panel=document.getElementById('panel');
let W=wrap.clientWidth, H=wrap.clientHeight;
svg.setAttribute('viewBox','0 0 '+W+' '+H);

const N=GRAPH.nodes.map((n,i)=>Object.assign({},n));
const idx={}; N.forEach((n,i)=>idx[n.id]=n);
const maxDeg=Math.max(...N.map(n=>n.degree));
// deterministic golden-angle seed placement (no RNG -> stable layout)
N.forEach((n,i)=>{const a=i*2.399963, r=Math.min(W,H)*0.34*Math.sqrt((i+0.5)/N.length);
  n.x=W/2+r*Math.cos(a); n.y=H/2+r*Math.sin(a); n.vx=0; n.vy=0;});
const E=GRAPH.edges.map(e=>({s:idx[e.source],t:idx[e.target],gloss:e.gloss,
  a:e.source,b:e.target}));
const adj={}; N.forEach(n=>adj[n.id]=new Set());
E.forEach(e=>{adj[e.a].add(e.b); adj[e.b].add(e.a);});
const rad=n=>10+ (n.degree/maxDeg)*18;

// ---- build SVG ----
const defs=document.createElementNS(SVGNS,'defs'); svg.appendChild(defs);
// prism gradient for the senses node (full-spectrum integration)
const pg=document.createElementNS(SVGNS,'linearGradient');
pg.setAttribute('id','prism'); pg.setAttribute('x1','0');pg.setAttribute('y1','0');
pg.setAttribute('x2','1');pg.setAttribute('y2','1');
['#e14b4b','#f4b43a','#4e9e7e','#3f7bd8','#8b5cf6'].forEach((c,i,arr)=>{
  const st=document.createElementNS(SVGNS,'stop');
  st.setAttribute('offset',(i/(arr.length-1)*100)+'%'); st.setAttribute('stop-color',c);
  pg.appendChild(st);});
defs.appendChild(pg);
const gLink=document.createElementNS(SVGNS,'g'); svg.appendChild(gLink);
const gNode=document.createElementNS(SVGNS,'g'); svg.appendChild(gNode);
E.forEach(e=>{const l=document.createElementNS(SVGNS,'line');
  l.setAttribute('class','link'); e.el=l; gLink.appendChild(l);
  l.addEventListener('mousemove',ev=>showTip(ev,
    '<b>'+e.s.label+' ↔ '+e.t.label+'</b><br>'+
    '<span style="color:var(--muted)">'+e.s.label+':</span> '+e.gloss[e.a]+'<br>'+
    '<span style="color:var(--muted)">'+e.t.label+':</span> '+e.gloss[e.b]));
  l.addEventListener('mouseleave',hideTip);});
N.forEach(n=>{const g=document.createElementNS(SVGNS,'g');
  g.setAttribute('class','node '+n.category+(n.degree>=6?' hub':''));
  const c=document.createElementNS(SVGNS,'circle'); c.setAttribute('r',rad(n));
  c.setAttribute('fill', n.hex==='prism'?'url(#prism)':(n.hex||'var(--emotion)'));
  const t=document.createElementNS(SVGNS,'text');
  t.textContent=(n.emoji?n.emoji+' ':'')+n.label;
  t.setAttribute('text-anchor','middle'); t.setAttribute('dy',-rad(n)-6);
  g.appendChild(c); g.appendChild(t); n.el=g; n.circle=c; n.text=t; gNode.appendChild(g);
  g.addEventListener('mouseenter',()=>focus(n));
  g.addEventListener('mouseleave',()=>{if(!pinned)unfocus();});
  g.addEventListener('click',()=>{pinned=n; focus(n); details(n);});
  addDrag(g,n);});

// ---- force sim ----
let alpha=1;
function tick(){
  const k=Math.sqrt(W*H/N.length)*0.42;
  for(let i=0;i<N.length;i++){const a=N[i];
    for(let j=i+1;j<N.length;j++){const b=N[j];
      let dx=a.x-b.x, dy=a.y-b.y, d=Math.hypot(dx,dy)||0.01;
      const f=(k*k/d)/d*alpha;
      dx*=f; dy*=f; a.vx+=dx; a.vy+=dy; b.vx-=dx; b.vy-=dy;}}
  E.forEach(e=>{let dx=e.t.x-e.s.x, dy=e.t.y-e.s.y, d=Math.hypot(dx,dy)||0.01;
    const f=(d-k)/d*0.5*alpha; dx*=f; dy*=f;
    e.s.vx+=dx; e.s.vy+=dy; e.t.vx-=dx; e.t.vy-=dy;});
  N.forEach(n=>{n.vx+=(W/2-n.x)*0.006*alpha; n.vy+=(H/2-n.y)*0.006*alpha;
    if(n===drag)return;
    n.x+=n.vx*0.85; n.y+=n.vy*0.85; n.vx*=0.82; n.vy*=0.82;
    const r=rad(n)+4; n.x=Math.max(r,Math.min(W-r,n.x)); n.y=Math.max(r+14,Math.min(H-r,n.y));});
  draw(); alpha*=0.985; if(alpha>0.02) requestAnimationFrame(tick);
}
function draw(){
  E.forEach(e=>{e.el.setAttribute('x1',e.s.x);e.el.setAttribute('y1',e.s.y);
    e.el.setAttribute('x2',e.t.x);e.el.setAttribute('y2',e.t.y);});
  N.forEach(n=>n.el.setAttribute('transform','translate('+n.x+','+n.y+')'));
}
function reheat(){alpha=1; requestAnimationFrame(tick);}

// ---- interaction ----
let pinned=null, drag=null;
function focus(n){const keep=new Set([n.id,...adj[n.id]]);
  N.forEach(m=>m.el.classList.toggle('dim',!keep.has(m.id)));
  E.forEach(e=>{const on=e.a===n.id||e.b===n.id;
    e.el.classList.toggle('hi',on); e.el.classList.toggle('dim',!on);});}
function unfocus(){N.forEach(m=>m.el.classList.remove('dim'));
  E.forEach(e=>e.el.classList.remove('hi','dim'));}
function details(n){
  let braids=E.filter(e=>e.a===n.id||e.b===n.id).map(e=>{
    const other=e.a===n.id?e.t:e.s, g=e.gloss[n.id];
    return '<p class="braid"><b>'+other.label+'</b> — '+g+'</p>';}).join('');
  const sw=n.hex==='prism'?'linear-gradient(135deg,#e14b4b,#f4b43a,#4e9e7e,#3f7bd8,#8b5cf6)':(n.hex||'#888');
  panel.innerHTML='<h2>'+(n.emoji?n.emoji+' ':'')+n.label+'</h2><div class="preset">preset: '+(n.preset||'—')+
    '</div><span class="chip"><span style="display:inline-block;width:10px;height:10px;border-radius:50%;background:'+sw+';margin-right:5px;vertical-align:middle"></span>'+(n.color||'')+
    '</span><span class="chip">'+n.category+'</span><span class="chip">degree '+n.degree+
    '</span>'+(n.somatic?'<div class="lbl">somatic seat</div><p style="margin:0 0 9px">'+n.somatic+'</p>':'')+
    (n.humor?'<div class="lbl">humor partner</div>'+n.humor:'')+
    '<div class="lbl">braids with</div>'+(braids||'<span class="empty">—</span>');
}
function addDrag(g,n){g.addEventListener('pointerdown',ev=>{drag=n; pinned=n;
  g.setPointerCapture(ev.pointerId); focus(n); details(n); ev.preventDefault();});
  g.addEventListener('pointermove',ev=>{if(drag!==n)return; const p=pt(ev);
    n.x=p.x; n.y=p.y; if(alpha<0.05){alpha=0.3;requestAnimationFrame(tick);} draw();});
  g.addEventListener('pointerup',ev=>{drag=null;});}
function pt(ev){const r=svg.getBoundingClientRect();
  return {x:(ev.clientX-r.left)/r.width*W, y:(ev.clientY-r.top)/r.height*H};}
function showTip(ev,html){tip.innerHTML=html; tip.style.opacity=1;
  tip.style.left=Math.min(ev.clientX+14,innerWidth-290)+'px';
  tip.style.top=(ev.clientY+14)+'px';}
function hideTip(){tip.style.opacity=0;}
svg.addEventListener('click',ev=>{if(ev.target===svg){pinned=null;unfocus();}});

document.getElementById('reheat').onclick=reheat;
document.getElementById('theme').onclick=()=>{
  const cur=document.documentElement.getAttribute('data-theme');
  const dark=cur? cur==='dark' : matchMedia('(prefers-color-scheme:dark)').matches;
  document.documentElement.setAttribute('data-theme',dark?'light':'dark');};
addEventListener('resize',()=>{W=wrap.clientWidth;H=wrap.clientHeight;
  svg.setAttribute('viewBox','0 0 '+W+' '+H); reheat();});
reheat();
</script>
</body>
</html>
"""

def norm(s):
    return ALIAS.get(s.strip().lower().strip('*:').strip())

def section(txt, head):
    m = re.search(r'## %s.*?\n(.*?)(?:\n## |\Z)' % re.escape(head), txt, re.S)
    return m.group(1) if m else ''

nodes, edge_map, errors = {}, {}, []

for d in sorted(glob.glob(os.path.join(FAM, '*'))):
    nid = os.path.basename(d)
    if nid not in NODES:
        continue
    txt = open(os.path.join(d, 'CONTEXT_GRAPH.md')).read()
    label = (re.search(r'^#\s*(.+?)\s*—\s*family map', txt, re.M) or [None, nid])[1]
    preset = (re.search(r'\*\*Preset name:\*\*\s*(.+?)\s*(?:·|\|)', txt) or [None, ''])[1].strip()
    emoji = (re.search(r'\*\*Emoji:\*\*\s*(.+?)\s*(?:·|\|)', txt) or [None, ''])[1].strip()
    color_line = (re.search(r'\*\*Color:\*\*\s*(.+)', txt) or [None, ''])[1]
    color_desc = re.split(r'\s*`', color_line, 1)[0].strip()
    htok = re.search(r'`(#[0-9A-Fa-f]{6}|prism)`', color_line)
    hexval = htok.group(1) if htok else '#888888'
    somatic = (re.search(r'\*\*Somatic seat:\*\*\s*(.+)', txt) or [None, ''])[1].strip()
    humor = ''
    hm = re.search(r'partners:\s*(.*?)(?:\n- |\Z)', section(txt, 'Humor edge'), re.S)
    if hm:
        humor = ', '.join(re.findall(r'\*\*(.+?)\*\*', hm.group(1))) or hm.group(1).strip()
    dual = 'cross-cutting' in txt.lower()
    braids = {}
    for line in section(txt, 'Braids with').splitlines():
        mm = re.match(r'\s*-\s*\*\*\+\s*(.+?)\*\*:?\s*(.*)', line)
        if not mm:
            continue
        raw = re.sub(r'\(.*?\)', '', mm.group(1))
        gloss = mm.group(2).strip().rstrip('*').strip()
        for part in re.split(r'=', raw):
            t = norm(part)
            if t and t != nid:
                braids[t] = gloss
    nodes[nid] = dict(id=nid, label=label, preset=preset, humor=humor,
                      emoji=emoji, color=color_desc, hex=hexval, somatic=somatic,
                      category='dual' if dual else 'emotion', braids=braids)

for a in NODES:
    for b, g in nodes[a]['braids'].items():
        if a not in nodes[b]['braids']:
            errors.append(f"asymmetric: {a} -> {b} (no reverse)")
        key = tuple(sorted((a, b)))
        edge_map.setdefault(key, {})[a] = g

if errors:
    print("GRAPH INTEGRITY FAILURE — machine view disagrees with the maps:")
    for e in errors:
        print("  " + e)
    sys.exit(1)

for nid in nodes:
    nodes[nid]['degree'] = sum(1 for k in edge_map if nid in k)
    nodes[nid].pop('braids')

edges = [dict(source=a, target=b, gloss={a: gl.get(a, ''), b: gl.get(b, '')})
         for (a, b), gl in sorted(edge_map.items())]

data = dict(
    title="emotions-and-humor — braid graph",
    note="Generated from families/*/CONTEXT_GRAPH.md by tools/build_graph.py. "
         "The markdown maps are the source of truth; this file is a projection.",
    nodes=[nodes[n] for n in NODES],
    edges=edges,
)

with open(os.path.join(ROOT, 'graph.json'), 'w') as f:
    json.dump(data, f, indent=2)

os.makedirs(os.path.join(ROOT, 'viz'), exist_ok=True)
with open(os.path.join(ROOT, 'viz', 'index.html'), 'w') as f:
    f.write(HTML.replace('__GRAPH_DATA__', json.dumps(data)))

print(f"ok: {len(data['nodes'])} nodes, {len(edges)} braids, symmetric ✓")
print("wrote graph.json and viz/index.html")
